image: golang:latest

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - build
  - test
  - acceptance_test
  - deploy

before_script:

go_build:
  stage: build
  script:
    - go build ./...

lint:
  stage: build
  script:
    - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin
    - go build ./...
    - golangci-lint run ./...

unit_test:
  stage: test
  script:
    - go install github.com/onsi/ginkgo/ginkgo
    - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress --skip="Stress"
    - go test -coverprofile=cover.out ./...
    - go tool cover -func=cover.out > coverage.out
    - tail coverage.out
