image: golang:latest

stages:
  - build
  - test

build:
  stage: build
  script: 
    - go build ./...

lint:
  stage: build
  script:
    - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.20.0
    - golangci-lint run

test_job:
  stage: test
  script:
    - go install github.com/onsi/ginkgo/ginkgo
    - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress --skip="Stress" --skipMeasurements -coverprofile=cover.out
    - go tool cover -func=cover.out > coverage.out
    - tail coverage.out
